[package]
name = "ssam"
version = "0.1.0"
authors = ["Maarten van Gompel <proycon@anaproy.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rand = "0.7.3"
rand_pcg = "0.2.1"
